MCU_SUB_VARIANT = nrf52840
CFLAGS += -DDEVICE_NAME='"TOWER_V2_OTA"'
CFLAGS += -DMOTA_INTERNAL_BOOTLOADER_UPDATE=1
CFLAGS += -DMOTA_SD_CARD=1
CFLAGS += -DMOTA_SD_DUAL_STORE=1
CFLAGS += -fno-caller-saves
CFLAGS += -DMOTA_SD_BOOTLOADER_UPDATE=1
