MCU_SUB_VARIANT = nrf52840
ifeq ($(RECOVERY_ALLOW_ALL_BOARDS),1)
CFLAGS += -DDEVICE_NAME='"3401_AUTO_DFU"'
else
CFLAGS += -DDEVICE_NAME='"3401_DFU"'
endif
CFLAGS += -DMOTA_QSPI_FLASH=1
CFLAGS += -DMOTA_RAK_AUTO_STORE=1
ifneq ($(RECOVERY_ALLOW_ALL_BOARDS),1)
CFLAGS += -DMOTA_INTERNAL_BOOTLOADER_UPDATE=1
endif
MOTA_RAM_ARENA_SIZE ?= 65536
